### ISSUE TITLE
🐛 [Bug]: reactnative集成报错 

### ISSUE THREAD

**Issue by wind-hx** [3lang3/react-vant#542]
### Which React Vant packages are impacted?

- [X] `react-vant` (React Vant core)
- [ ] `react-vant-icons`(React Vant Icon)

### What version of React Vant are you using?

3.0.0-rc.6

### Descripition

集成后启动报错
```
error: Error: Unable to resolve module ./base.css from /Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/react-vant/lib/styles/index.js: 

None of these files exist:
  * node_modules/react-vant/lib/styles/base.css(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-vant/lib/styles/base.css/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  11 | }
  12 |
> 13 | require("./base.css");
     |          ^
  14 |
  15 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
    at ModuleResolver.resolveDependency (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at async addDependency (/Volumes/wind_ssd/project/react-native-project/capital/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
    at async Promise.all (index 1)

```

**Comment by 3lang3** [comment]
暂不支持 rn 哈
